# Generated by Django 5.1.3 on 2024-12-09 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_modification_car_user_filling_car_modifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filling',
            options={},
        ),
    ]
